#!/bin/sh
set -e
./test-rust
echo " -- doing final fmt/clippy : calculator --"
cd examples/rust/calculator
cargo fmt
cargo clippy
cd ../../..
echo " -- doing final fmt/clippy/MSRV check: lib --"
cd rust
cargo +1.54.0-x86_64-unknown-linux-gnu check --all-features
cargo fmt
cargo clippy
cargo semver-checks
