#!/bin/sh
set -e
cd rust
# check the expected configs
# this build checks that no_std was properly applied - v1.0.1 appears to have had an incident like that
cargo build --target armv7a-none-eabi --no-default-features
cargo test --no-default-features -F detailed_errors --no-run
cargo test --no-default-features -F alloc --no-run
cargo test --no-default-features -F _experimental,serde --no-run
cargo test --no-default-features -F _experimental,serde,alloc --no-run
cargo test --all-features
cargo doc --all-features
cargo tarpaulin --all-features
cargo build --all-features
cd ../examples/rust/calculator
cargo build
cd ../serdetest
cargo build
cd ../../..
mdbook test doc -L rust/target/debug/deps/
# also check: cargo semver-checks
