[package]
name = "datum-serdetest"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
datum = { path = "../../../rust", features = ["_experimental", "serde"] }
serde = { version = "1.0.209", features = ["std", "derive"] }
